apiVersion: apps/v1
kind: Deployment
metadata:
  name: rekviziti-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rekviziti
  template:
    metadata:
      labels:
        app: rekviziti
    spec:
      containers:
        - image: ts4894/rekviziti:2022-01-02-21-59-06
          name: rekviziti
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              valueFrom:
                secretKeyRef:
                  name: pg-pas-rekviziti
                  key: password
          ports:
            - containerPort: 8085
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: rekviziti
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      protocol: TCP
      targetPort: server
  selector:
    app: rekviziti