kumuluzee:
  name: rekviziti-service
  env:
    name: dev
  version: 1.0.0
  cors-filter:
    annotations:
      my-resource:
        allow-origin: "http://kumuluz.com"
        allow-subdomains: false
  server:
    base-url: https://20.88.176.138:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/RekvizitiMetadataDS
      connection-url: jdbc:postgresql://rekviziti-db.postgres.database.azure.com:5432/postgres?user=postgresAdmin&password=RekvizitiDBPass123&sslmode=require
      username: postgresAdmin
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/RekvizitiMetadataDS
    metrics:
      web-instrumentation:
        - name: rekviziti-endpoint
          url-pattern: /v1/rekviziti/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="b018540f-f4da-408b-afe6-d9e1251ff783-ls.logit.io"
                                  port="24836" protocol="udp">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="trace" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  rest-client:
    registrations:
      - class: rekviziti-processing-api
        url: https://localhost:8085/v1
        read-timeout: 5000
rest-properties:
  maintenance-mode: false
  broken: false
app-properties:
  amazon-rekognition:
    access-key:
    secret-key:

uporabniki-storitev:
  url: "https://20.85.248.6:8083/"
  enabled: false
  watch: true